# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase Deployment

on:
  push:
    branches: [ master ]

jobs:
  firebase_hosting:
    name: "Firebase Hosting"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm --prefix "./post-wall" install &
          npm -g install firebase-tools
          
      - name: Build
        run: |
          npm --prefix "./post-wall" run build
      
      - name: Deploy
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting
        
  firebase_cloud_functions:
    
    name: "Firebase Cloud Functions"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm --prefix "./functions" install &
          npm -g install firebase-tools
      
      - name: Deploy
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only functions
